spring:
  application:
    name: ServiceRegistration
  profiles:
    active: dev,us-east-2a 
server:
  port: 8761 
eureka:
  client:
    datacenter: cloud
    awsAccessId: AKIAVAAFTNPUSX67XFUW
    awsSecretKey: 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
    register-with-eureka: false
    fetch-registry: false
    region: us-east-2
    service-url:
      us-east-2a: http://3.135.246.248:8761/eureka/v2/
      us-east-2b: http://18.216.8.188:8761/eureka/v2/
      us-east-2c: http://3.19.141.231:8761/eureka/v2/
    availability-zones:
      us-east-2: us-east-2a,us-east-2a,us-east-2c
    # serviceUrl:defaultZone: http://localhost:8761/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 0     
  
    
/*
 #eureka.shouldUseDns=true
 #eureka.eurekaServer.domainName=mydomaintest.netflix.net
 #eureka.eurekaServer.port=7001
 #eureka.eurekaServer.context=eureka/v2*/
